{% set name = "nagl" %}
{% set version = "0.0.1a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simonboothroyd/{{ name }}/archive/{{ version | replace("a", "-alpha.") }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - nagl = nagl.cli:cli

requirements:
  host:
    - python
    - pip

  run:
    - python

      # Core dependencies
    - click
    - click-option-group
    - pydantic
    - pytorch-cpu
    - dgl
test:
  imports:
    - nagl

about:
  home: https://github.com/simonboothroyd/nagl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Graph convolutional networks learning molecular force fields.'
  description: |
    A framework for applying graph convolutional networks to molecules,
    with a focus on learning continuous "atom-type" embeddings and from
    these classical molecule force field parameters.
  dev_url: https://github.com/simonboothroyd/nagl

extra:
  recipe-maintainers:
    - SimonBoothroyd
